image: Visual Studio 2015
environment:
  PATH: '%PATH%;C:\texlive\2017\bin\win32'
install:
  - bash ./install-tex.sh
cache:
  - 'C:\texlive\2017\texmf-var\fonts\cache'
build_script:
  - tlmgr install collection-langjapanese
  - platex -v
